
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: root
  password: <%= Rails.application.credentials.mysql[:password] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: BookStore_development

test:
  <<: *default
  database: BookStore_test

production:
  <<: *default
  database: BookStore_production
